[package]
name = "example-hello-toasty-pgsql"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
toasty = { path = "../../src/toasty" }
toasty-pgsql = { path = "../../src/db/pgsql" }

postgres.workspace = true
tokio.workspace = true
