[package]
name = "toasty-core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
indexmap.workspace = true
postgres = { workspace = true, optional = true }
std-util.workspace = true
tokio-stream.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true

[features]
default = []
postgres = ["dep:postgres"]
